# Generated by Django 6.0.5 on 2026-06-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_manfacture', models.IntegerField()),
                ('p_exp', models.IntegerField()),
                ('p_mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
